/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_Image */

#ifndef _Included_gui_Image
#define _Included_gui_Image
#ifdef __cplusplus
extern "C" {
#endif
#undef gui_Image_FOCUS_TRAVERSABLE_UNKNOWN
#define gui_Image_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef gui_Image_FOCUS_TRAVERSABLE_DEFAULT
#define gui_Image_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef gui_Image_FOCUS_TRAVERSABLE_SET
#define gui_Image_FOCUS_TRAVERSABLE_SET 2L
#undef gui_Image_TOP_ALIGNMENT
#define gui_Image_TOP_ALIGNMENT 0.0f
#undef gui_Image_CENTER_ALIGNMENT
#define gui_Image_CENTER_ALIGNMENT 0.5f
#undef gui_Image_BOTTOM_ALIGNMENT
#define gui_Image_BOTTOM_ALIGNMENT 1.0f
#undef gui_Image_LEFT_ALIGNMENT
#define gui_Image_LEFT_ALIGNMENT 0.0f
#undef gui_Image_RIGHT_ALIGNMENT
#define gui_Image_RIGHT_ALIGNMENT 1.0f
#undef gui_Image_serialVersionUID
#define gui_Image_serialVersionUID -7644114512714619750i64
#undef gui_Image_serialVersionUID
#define gui_Image_serialVersionUID -2284879212465893870i64
/*
 * Class:     gui_Image
 * Method:    loadBMPImage
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gui_Image_loadBMPImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gui_Image
 * Method:    exportBMPImage
 * Signature: ([BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gui_Image_exportBMPImage
  (JNIEnv *, jobject, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
